cpus: 6
publish_dir_mode: symlink
size: 0.1
custom_profile: "path/to/profile"
mean_len: 150
frag_len: 270
frag_sd: 27
seed: 42
mu: 1
sigma: 2
custom_range: "1,2,3,4,5,6,7,8,9,10,15,20,25,50,100,150,200,250,300,400,500"
nb: 1
step: 1
start: 1
summary: "path/to/assembly/summary"
config: "path/to/default/config"
